/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(1)                                                        */
/* BINDTOOL_HEADER_FILE(verilog_axi_ss.h)                                          */
/* BINDTOOL_HEADER_FILE_HASH(78d518a7da29e3f42307301fe783be14)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/verilog/verilog_axi_ss.h>
// pydoc.h is automatically generated in the build directory
#include <verilog_axi_ss_pydoc.h>

void bind_verilog_axi_ss(py::module& m)
{

    using verilog_axi_ss    = gr::verilog::verilog_axi_ss;


    py::class_<verilog_axi_ss, gr::block, gr::basic_block,
        std::shared_ptr<verilog_axi_ss>>(m, "verilog_axi_ss", D(verilog_axi_ss))

        .def(py::init(&verilog_axi_ss::make),
           D(verilog_axi_ss,make)
        )




        ;




}








